### ISSUE TITLE
Save personal details - Name

### ISSUE THREAD

**Issue by marcusbory** [AY2122S1-CS2113T-T09-1/tp#13]
As a user, I can save my Name locally so that the application is aware of the user.

**Comment by ng-andre** [comment]
@AY2122S1-CS2113T-T09-1/developers change the format from /g [github] to -g [github]

**Comment by marcusbory** [comment]
Changing this to high priority since we are now in V2.0. Also updating type to Story instead of Enhancement, since this corresponds to our digital name card.
