### ISSUE TITLE
[PE-D] No input validation for search

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-1/tp#147]
![image.png](https://raw.githubusercontent.com/lixiyuan416/ped/main/files/7e769cbf-e54d-4d82-9e16-59bcc389f2dc.png)

-Nice to have in case user types in the wrong flag by accident and wonders why he sees no results

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: lixiyuan416/ped#2

**Comment by ashrafjfr** [comment]
As you have said, this is a nice to have feature. In general, even for search engines, if you search for something, you will get what you search for. Normally when you search for something, you will type in a string that is included in the actual search result that you are looking for. However, we appreciate your input. Thanks, Bane!
