### ISSUE TITLE
[PE-D] No duplicate checking of adding "me"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-1/tp#154]
When adding new contacts, if the new contact to be added has exactly the same fields as "me", there is no check for the duplicate. This is a minor problem, but I guess it is better to add duplicate checking, just in case someone adds himself wrongly to the contact.

![image.png](https://raw.githubusercontent.com/haoyusimon/ped/main/files/75269258-ff81-4aea-a0ce-35b6611d8724.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: haoyusimon/ped#3

**Comment by ashrafjfr** [comment]
We don't think this is necessary for our programme. While it may not be complicated to implement, the semantics of our personal contact is separate from our Contact List. Even if regular contact management applications, such as the one in your phone, the personal details and the contact book is separate. Thank you for your opinion! :)
